services:
  server:
    build: ./Backend
    ports:
      - '8000:8000'
    volumes:
      - ./public/uploads:/app/public/uploads
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  client:
    build:
      context: ./Frontend
    ports:
      - '80:80'
    volumes:
      - ./public/uploads:/app/public/uploads
    env_file:
      - .env
    environment:
      VITE_API_URL: http://mycitadel.ddns.net:8000/
    networks:
      - app-network

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Nurik123"
      POSTGRES_DB: "exam"
      POSTGRES_SCHEMA: "exam12"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
volumes:
  db-data:

networks:
  app-network:
    driver: bridge
