openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
paths:
  /auth/sign-in:
    post:
      summary: Sign in a user
      operationId: signIn
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User signed in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Invalid credentials
  /auth/sign-up:
    post:
      summary: Sign up a user
      operationId: signUp
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                name: 
                  type: string
                surname:
                  type: string
      responses:
        '200':
          description: User signed in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Invalid credentials
  /auth/sign-out:
    delete:
      summary: Sign out a user
      operationId: signOut
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: User signed out
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /blog/get:
    get:
      summary: Get all blogs
      operationId: getAllBlogs
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: All blogs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Blog'
  /blog/add:
    post:
      summary: Add a new blog
      operationId: addBlog
      security:
        - apiKeyAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                media:
                  type: string
      responses:
        '200':
          description: The created blog
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
        '400':
          description: Validation errors
  /blog/delete/{id}:
    delete:
      summary: Delete blog
      operationId: deleteBlog
      security:
        - apiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Blog deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
        '404':
          description: Blog not found
  /blog/patch/{id}:
    patch:
      summary: Patch blog
      operationId: patchBlog
      security:
        - apiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                media:
                  type: string
      responses:
        '200':
          description: Blog patch
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Blog'
        '404':
          description: Blog not found
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        name:
          type: string
        surname:
          type: string
    Blog:
      type: object
      properties:
        id:
          type: integer
        text:
          type: string
        media:
          type: string
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: "JWT token for authorization"